### ISSUE TITLE
Сделать ссылки в тексте задания дз кликабельными

### ISSUE THREAD

**Issue by PowerLay** [MinusD/MBC-d.ru#3]
Добрый вечер!
Было бы не плохо если при ссылки можно было бы открывать по нажатию. Сейчас можно открыть по выделению или скопировав ссылку.
В ссылки обычно мы прикрепляем файлы с гугл диска. Альтернативным решением было бы поле с ссылкой. Если у дз указана ссылка то у дз появляется кнопка которая ведет на эту ссылку.

**Comment by MinusD** [comment]
Идея хорошая, подумаем как лучше её реализовать!

**Comment by MinusD** [comment]
![image](https://user-images.githubusercontent.com/50549999/189476645-716851d7-78f5-4803-8069-129c4e55c057.png)
Добавлена возможность добавлять ссылки, для этого оберните ссылку в квадратные скобочки и при просмотре задания снизу появится список всех ссылок в тексте задания. 

Если ссылка не отображается, для оперативного ответа пишите сюда: [t.me/mbcs_admin](t.me/mbcs_admin)

P.s. Внутри квадратных скобок не должно быть **ни одного пробела**, иначе ссылка будет не кликабельна.
